#!/bin/bash

#Frist generate potential files 
cp result_HWW_W.xyz watpot
cd watpot
./a
cd ../
cp result_HWW_W.xyz hwwpot
cd hwwpot
./a
cd ../

#Then start to analyze result
make 
./xget.x  result_HWW_W.xyz 


